
export const courses = [
    {
      department: "Graphic & Multimedia",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
    {
      department: "Web & software",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
    {
      department: "Digital marketing",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
    {
      department: "3D animation",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
    {
      department: "Robotics & Automation",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
    {
      department: "Cyber Security",
      icon: "https://i.ibb.co/pytF02F/graphic-design.png",
      courses: [
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
        {
          name: "Professional Graphic Design",
          ratings: "5",
          student: "1200",
          courseFee: "15000",
          img: "https://i.ibb.co/VYdXhVZ/graphic-courses.jpg",
          duration: "6",
          lectures: "48",
          projects: "10",
          bio: "Considering the growing demand for visual content, marketers are promoting their products through graphical ideas nowadays. The increasing need for graphic designers has unlocked many opportunities for the people who prefer working independently. A study shows, all the companies prioritize their visual acceptance, even a small company spends up to 500 dollars to create a perfect logo. If you are passionate about making designs, this updated Graphic Design course is for you.",
          overview:
            "Our updated curriculum, along with the project-based work, prepares you to be a Professional Graphic Designer. The course module covers a wide range of topics, through which you learn how to use digital tools to create unique designs. Using Adobe Photoshop or Adobe Illustrator, you will be able to design a variety of things including banners, t-shirts, products, etc during the course. The lab facilities that we provide make you competent to perform better in the global marketplace. So, if you are interested to explore the field of innovative designs, enroll in this course now. ",
          syllabus: [
            "Professional Presentation",
            "Invoice Template Design",
            "Brochure Layout",
            "Desk & Wall Calendar Design",
            "Certificate Template Design",
            "Resume & Cover Letter Design",
            "Image Clipping",
            "Banner / Poster Design",
            "Web Banner Design",
            "Raster To Vector",
            "Letterhead Design",
            "Logo Design",
            "Product Packaging",
            "T-Shirt Design",
            "Landscape Design",
            "Neck Joint",
            "Magazine Design",
            " Web UI Design",
          ],
          instructor: {
              name: "Mehetaj",
              exp: "7",
              email: "abc@xyz.com",
              student: "10000",
              courses: "",
              image: "",
          },
        },
      ],
    },
  ];
  